# Generated by Django 4.2.16 on 2026-06-25 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HYPERTENSION', 'Hypertension'), ('BLEEDING', 'Saignement'), ('PRETERM_RISK', "Risque d'accouchement prématuré"), ('GESTATIONAL_DIABETES', 'Diabète gestationnel'), ('OTHER', 'Autre complication')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Accusée de réception'), ('RESOLVED', 'Résolue')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(help_text="Description détaillée de l'alerte")),
                ('action_taken', models.TextField(blank=True, help_text='Actions réalisées', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alerts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('reason', models.TextField(help_text='Motif de la consultation')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('CONFIRMED', 'Confirmé'), ('COMPLETED', 'Effectué'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes du soignant', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action réalisée', max_length=100)),
                ('description', models.TextField(help_text='Description détaillée')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField(auto_now_add=True)),
                ('report', models.TextField(help_text='Compte-rendu médical de la consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consultations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FollowUpSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'follow_up_schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('BLOOD', 'Prise de sang'), ('URINE', "Analyse d'urine"), ('ULTRASOUND', 'Échographie'), ('BLOOD_PRESSURE', 'Tension artérielle'), ('WEIGHT', 'Poids'), ('OTHER', 'Autre')], max_length=20)),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('result_summary', models.TextField(help_text='Résumé des résultats')),
                ('details', models.JSONField(blank=True, help_text='Détails structurés en JSON', null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='exams/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_exams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date des dernières règles (DDR)')),
                ('expected_delivery_date', models.DateField(help_text="Date prévue d'accouchement (DPA)")),
                ('is_active', models.BooleanField(default=True, help_text='Grossesse en cours')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pregnancies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('PATIENTE', 'Patiente'), ('SOIGNANT', 'Soignant'), ('ADMIN', 'Administrateur')], default='PATIENTE', max_length=20)),
                ('speciality', models.CharField(blank=True, help_text='Spécialité du soignant (ex: Gynécologue, Sage-femme)', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Tension systolique (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Tension diastolique (mmHg)', null=True)),
                ('uterine_height', models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur utérine (cm)', max_digits=5, null=True)),
                ('fetal_heart_rate', models.IntegerField(blank=True, help_text='Fréquence cardiaque fœtale (bpm)', null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.consultation')),
            ],
            options={
                'db_table': 'vital_signs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCaregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Soignant principal')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='api.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_assignments', to='api.user')),
            ],
            options={
                'db_table': 'user_caregivers',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='api.user'),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.consultation'),
        ),
        migrations.AddField(
            model_name='followupschedule',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_schedule', to='api.pregnancy'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.appointment'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_caregiver', to='api.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to='api.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.pregnancy'),
        ),
        migrations.AddField(
            model_name='alert',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.consultation'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['consultation'], name='vital_signs_consult_f11d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='usercaregiver',
            index=models.Index(fields=['patient'], name='user_caregi_patient_8dd318_idx'),
        ),
        migrations.AddIndex(
            model_name='usercaregiver',
            index=models.Index(fields=['caregiver'], name='user_caregi_caregiv_d6136c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercaregiver',
            index=models.Index(fields=['is_primary'], name='user_caregi_is_prim_bac2e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercaregiver',
            constraint=models.UniqueConstraint(fields=('patient', 'caregiver'), name='unique_assignment'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['patient'], name='pregnancies_patient_40565f_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['is_active'], name='pregnancies_is_acti_7b7da1_idx'),
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'is_active'), name='unique_active_pregnancy'),
        ),
        migrations.AddIndex(
            model_name='medicalexam',
            index=models.Index(fields=['consultation'], name='medical_exa_consult_706527_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalexam',
            index=models.Index(fields=['exam_type'], name='medical_exa_exam_ty_c3655b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalexam',
            index=models.Index(fields=['is_abnormal'], name='medical_exa_is_abno_c911f5_idx'),
        ),
        migrations.AddIndex(
            model_name='followupschedule',
            index=models.Index(fields=['pregnancy'], name='follow_up_s_pregnan_0b685f_idx'),
        ),
        migrations.AddIndex(
            model_name='followupschedule',
            index=models.Index(fields=['scheduled_date'], name='follow_up_s_schedul_42a172_idx'),
        ),
        migrations.AddIndex(
            model_name='followupschedule',
            index=models.Index(fields=['is_completed'], name='follow_up_s_is_comp_bf61b6_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['appointment'], name='consultatio_appoint_343bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='appointment_patient_75a4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['caregiver'], name='appointment_caregiv_a4e556_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date_time'], name='appointment_date_ti_e88168_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['consultation'], name='alerts_consult_2c85d2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='alerts_alert_t_eda531_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_severit_362484_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_status_0e4dc1_idx'),
        ),
    ]
