# Generated by Django 4.2.16 on 2026-06-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('HYPERTENSION', 'Hypertension'), ('BLEEDING', 'Saignement'), ('PRETERM_RISK', "Risque d'accouchement prématuré"), ('GESTATIONAL_DIABETES', 'Diabète gestationnel'), ('OTHER', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Accusée'), ('RESOLVED', 'Résolue')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='report',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='result_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercaregiver',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='fetal_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='uterine_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
